@startuml

title __PACMAN-JAVA's Class Diagram__\n

  namespace Controller {
    class Controller.BindingController {
    }
  }
  

  namespace Controller {
    class Controller.EventController {
    }
  }
  

  namespace Controller {
    class Modele.ThreadController {
    }
  }
  

  namespace Modele {
    enum Depl {
    }
  }
  

  namespace Modele {
    abstract class Modele.Entity {
    }
  }
  

  namespace Modele {
    class Modele.Ghost {
    }
  }
  

  namespace Modele {
    class Modele.ModelGrid {
    }
  }
  

  namespace Modele {
    enum ObjDynam {
    }
  }
  

  namespace Modele {
    enum ObjStatic {
    }
  }
  

  namespace Modele {
    class Modele.SimplePacMan {
    }
  }
  

  namespace VueTasks {
    class VueTasks.DisplayThread {
    }
  }
  

  namespace VueTasks {
    class VueTasks.EndOfGameTask {
    }
  }
  

  namespace VueTasks {
    class VueTasks.LivesTask {
    }
  }
  

  namespace Vue {
    class Vue.MainVue {
    }
  }
  

  Controller.EventController o-- Modele.ModelGrid : modelGrid
  Controller.EventController o-- Modele.SimplePacMan : spm
  Controller.EventController o-- Modele.ThreadController : threadController
  Modele.ThreadController o-- VueTasks.DisplayThread : displayThread
  Modele.ThreadController o-- VueTasks.EndOfGameTask : endOfGameTask
  Modele.ThreadController o-- Modele.ModelGrid : modelGrid
  Modele.ThreadController o-- Controller.BindingController.direction : paneDirection
  Modele.Entity o-- Modele.Depl : direction
  Modele.Entity o-- Modele.ModelGrid : modelGrid
  Modele.Ghost -up-|> Modele.Entity
  Modele.SimplePacMan -up-|> Modele.Entity
  Modele.SimplePacMan o-- Modele.Depl : cachedDirection
  VueTasks.DisplayThread -up-|> javafx.concurrent.Task
  VueTasks.DisplayThread o-- Modele.ModelGrid : modelGrid
  VueTasks.EndOfGameTask -up-|> javafx.concurrent.Task
  VueTasks.EndOfGameTask o-- Modele.ThreadController : controller
  VueTasks.EndOfGameTask o-- Modele.ModelGrid : modelGrid
  VueTasks.LivesTask -up-|> javafx.concurrent.Task
  VueTasks.LivesTask o-- Modele.SimplePacMan : simplePacMan
  Vue.MainVue -up-|> javafx.application.Application


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
