@startuml

title __PACMAN-JAVA's Class Diagram__\n

  namespace Controller {
    class Controller.BindingController {
    }
  }
  

  namespace Controller {
    class Controller.EventController {
    }
  }
  

  namespace Controller {
    class Controller.ThreadController {
    }
  }
  

  namespace Modele {
    enum Depl {
    }
  }
  

  namespace Modele {
    abstract class Modele.Entity {
    }
  }
  

  namespace Modele {
    class Modele.Ghost {
    }
  }
  

  namespace Modele {
    class Modele.ModelGrid {
    }
  }
  

  namespace Modele {
    enum ObjDynam {
    }
  }
  

  namespace Modele {
    enum ObjStatic {
    }
  }
  

  namespace Modele {
    class Modele.SimplePacMan {
    }
  }
  

  namespace TasksThreads {
    class TasksThreads.DisplayThread {
    }
  }
  

  namespace TasksThreads {
    class TasksThreads.EndOfGameTask {
    }
  }
  

  namespace TasksThreads {
    class TasksThreads.LivesTask {
    }
  }
  

  namespace Vue {
    class Vue.MainVue {
    }
  }
  

  Controller.EventController o-- Modele.ModelGrid : modelGrid
  Controller.EventController o-- Modele.SimplePacMan : spm
  Controller.EventController o-- Controller.ThreadController : threadController
  Controller.ThreadController o-- TasksThreads.DisplayThread : displayThread
  Controller.ThreadController o-- TasksThreads.EndOfGameTask : endOfGameTask
  Controller.ThreadController o-- Modele.ModelGrid : modelGrid
  Controller.ThreadController o-- Controller.BindingController.direction : paneDirection
  Modele.Entity o-- Modele.Depl : direction
  Modele.Entity o-- Modele.ModelGrid : modelGrid
  Modele.Ghost -up-|> Modele.Entity
  Modele.SimplePacMan -up-|> Modele.Entity
  Modele.SimplePacMan o-- Modele.Depl : cachedDirection
  TasksThreads.DisplayThread -up-|> javafx.concurrent.Task
  TasksThreads.DisplayThread o-- Modele.ModelGrid : modelGrid
  TasksThreads.EndOfGameTask -up-|> javafx.concurrent.Task
  TasksThreads.EndOfGameTask o-- Controller.ThreadController : controller
  TasksThreads.EndOfGameTask o-- Modele.ModelGrid : modelGrid
  TasksThreads.LivesTask -up-|> javafx.concurrent.Task
  TasksThreads.LivesTask o-- Modele.SimplePacMan : simplePacMan
  Vue.MainVue -up-|> javafx.application.Application


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
