@startuml

title __CONTROLLER's Class Diagram__\n

  namespace Controller {
    class Controller.BindingController {
        {static} + bindText()
    }
  }
  

  namespace Controller {
    enum direction {
      BOTTOM
      LEFT
      RIGHT
      TOP
    }
  }
  

  namespace Controller {
    class Controller.EventController {
        - diffs : ObservableList<Menu>
        - lifetab : ImageView[]
        - tab : ImageView[][]
        + EventController()
        + handleRestart()
        + handleStop()
        + moveDown()
        + moveLeft()
        + moveRight()
        + moveUp()
        + setBindings()
        + setMenus()
        - getDifficulty()
        - getGhosts()
        - reset()
    }
  }
  

  namespace Controller {
    class Controller.ThreadController {
        - borderPane : BorderPane
        - entities : ArrayList<Entity>
        - text : Text
        - threads : ArrayList<Thread>
        + ThreadController()
        + interruptThreads()
        + resetGrid()
        + resetThreads()
        + setEndText()
        + startThreads()
        + stopAll()
        + stopGame()
        - resetTextBinding()
    }
  }
  

  Controller.BindingController +-down- Controller.BindingController.direction
  Controller.EventController o-- Modele.ModelGrid : modelGrid
  Controller.EventController o-- Modele.SimplePacMan : spm
  Controller.EventController o-- Controller.ThreadController : threadController
  Controller.ThreadController o-- TasksThreads.DisplayThread : displayThread
  Controller.ThreadController o-- TasksThreads.EndOfGameTask : endOfGameTask
  Controller.ThreadController o-- Modele.ModelGrid : modelGrid
  Controller.ThreadController o-- Controller.BindingController.direction : paneDirection


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
